"use client"
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'

const slides = [
  {image:'/images/hero-livingroom-camera.jpg',alt:'IM Cam video call camera in a bright living room',eyebrow:'IM Cam · stay close',title:'See and speak across every distance.',copy:'Simple video connection for children, older family members and pets.',position:'object-[78%_center] md:object-[64%_center]',align:'items-start text-left'},
  {image:'/images/hero-car-translator.jpg',alt:'IM Mate translator in a vehicle',eyebrow:'IM Mate · speak freely',title:'Make every conversation feel local.',copy:'Two-way AI translation for service teams, meetings and mobile work.',position:'object-[82%_center] md:object-[66%_center]',align:'items-start text-left'},
  {image:'/images/hero-factory-line.jpg',alt:'Smart communication devices in a technical development setting',eyebrow:'Built around communication',title:'One platform. Two ways to connect.',copy:'Translation and video hardware shaped by focused product engineering.',position:'object-[24%_center] md:object-[34%_center]',align:'items-end text-right'},
]

export function HeroCarousel(){const[index,setIndex]=useState(0);useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const id=setInterval(()=>setIndex(i=>(i+1)%slides.length),6500);return()=>clearInterval(id)},[]);const s=slides[index];return <section className="relative min-h-[560px] overflow-hidden bg-slate-950 text-white md:min-h-[620px]"><Image key={s.image} src={s.image} alt={s.alt} fill priority className={`object-cover ${s.position}`}/><div className="pointer-events-none absolute inset-0 bg-gradient-to-r from-slate-950/95 via-slate-950/55 to-slate-950/10 md:from-slate-950/85 md:via-slate-950/45 md:to-slate-950/20"/><div className={`relative mx-auto flex min-h-[560px] max-w-7xl flex-col justify-center px-6 py-20 md:min-h-[620px] md:py-24 ${s.align}`}><div className="motion-safe:animate-[hero-in_.6s_ease-out] max-w-[72%] md:max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-300 md:text-sm md:tracking-[.24em]">{s.eyebrow}</p><h1 className="mt-4 text-balance text-4xl font-bold leading-tight sm:text-5xl md:mt-5 md:text-7xl">{s.title}</h1><p className="mt-5 text-sm leading-6 text-slate-100 md:mt-6 md:text-lg">{s.copy}</p><div className={`mt-7 flex flex-col items-start gap-3 md:mt-9 md:flex-row md:flex-wrap ${index===2?'md:justify-end':''}`}><Link className="rounded-lg bg-cyan-400 px-5 py-2.5 text-sm font-semibold text-slate-950 md:px-6 md:py-3 md:text-base" href="/products">Explore devices</Link><Link className="rounded-lg border border-white/60 bg-slate-950/35 px-5 py-2.5 text-sm font-semibold md:px-6 md:py-3 md:text-base" href="/contact">Request a quote</Link></div></div></div><div className="absolute bottom-6 left-1/2 flex -translate-x-1/2 gap-2" aria-label="Hero slides">{slides.map((slide,i)=><button key={slide.image} onClick={()=>setIndex(i)} aria-label={`Show slide ${i+1}`} aria-current={i===index} className={`h-2.5 rounded-full transition-all ${i===index?'w-8 bg-cyan-300':'w-2.5 bg-white/60'}`}/>)}</div></section>}
