import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'
import { createRequire } from 'node:module'
const require = createRequire('D:\\Cursor\\Grand\\huanqiu-admin\\package.json')
const { createClient } = require('v0-sdk')
const mode=process.argv[2]||'doctor', root='D:/Cursor/Grand/immate', teamId='team_v0pxRIIzSUGJleUTRNSz6GS4'
for(const p of ['.env','.env.local','_migrate-batch/.env']) if(existsSync(p)) for(const line of readFileSync(p,'utf8').split(/\r?\n/)){const i=line.indexOf('=');if(i<1||line.trim().startsWith('#'))continue;process.env[line.slice(0,i).trim()]??=line.slice(i+1).trim().replace(/^['"]|['"]$/g,'')}
const apiKey=process.env.V0_API_KEY||process.env.V0_TOKEN;if(!apiKey||!apiKey.includes(teamId))throw new Error('Missing required-team v0 key')
const v0=createClient({apiKey}), statePath=`${root}/.codex-delivery/v0-state.json`, prompt=readFileSync(`${root}/.codex-delivery/v0-prompt.md`,'utf8'), assets=JSON.parse(readFileSync(`${root}/.codex-delivery/v0-asset-urls.json`,'utf8')).assets.map(a=>a.url)
if(mode==='doctor'){const user=await v0.user.get();console.log(JSON.stringify({ok:true,userId:user?.id??null,requiredTeam:teamId,attachmentCount:assets.length,promptBytes:Buffer.byteLength(prompt)}));process.exit()}
if(mode==='create'){if(existsSync(statePath))throw new Error('v0 state already exists');const project=await v0.projects.create({name:'immate',description:'IM Mate and IM Cam B2B smart communication devices'});const chat=await v0.chats.create({projectId:project.id,message:prompt,attachments:assets.map(url=>({url})),chatPrivacy:'private',responseMode:'async',modelConfiguration:{imageGenerations:false}});const state={teamId,projectId:project.id,chatId:chat.id,webUrl:chat.webUrl,createdAt:new Date().toISOString(),attachments:assets};writeFileSync(statePath,JSON.stringify(state,null,2)+'\n','utf8');console.log(JSON.stringify({projectId:state.projectId,chatId:state.chatId,webUrl:state.webUrl}));process.exit()}
if(mode==='status'||mode==='download'){const state=JSON.parse(readFileSync(statePath,'utf8')),chat=await v0.chats.getById({chatId:state.chatId}),versionId=chat.latestVersion?.id,status=chat.latestVersion?.status;if(mode==='status'){console.log(JSON.stringify({projectId:state.projectId,chatId:state.chatId,webUrl:state.webUrl,chatKeys:Object.keys(chat),versionId,status,demoUrl:chat.latestVersion?.demoUrl??null,messageCount:chat.messages?.length??null,messages:chat.messages?.slice(-2).map(m=>({role:m.role,type:m.type,status:m.status,content:typeof m.content==='string'?m.content.slice(0,200):null}))??[]}));process.exit()}if(!versionId||status!=='completed')throw new Error(`Latest version not ready: ${versionId}/${status}`);const data=Buffer.from(await v0.chats.downloadVersion({chatId:state.chatId,versionId,format:'zip',includeDefaultFiles:true})),archive=`${root}/.codex-delivery/source/immate-v0.zip`;mkdirSync(dirname(archive),{recursive:true});writeFileSync(archive,data);Object.assign(state,{versionId,demoUrl:chat.latestVersion?.demoUrl??null,archivePath:archive,downloadedAt:new Date().toISOString()});writeFileSync(statePath,JSON.stringify(state,null,2)+'\n','utf8');console.log(JSON.stringify({archive,bytes:data.length,versionId,demoUrl:state.demoUrl}));process.exit()}
throw new Error(`Unknown mode ${mode}`)
