import { createClient } from '@supabase/supabase-js'
import bcrypt from 'bcryptjs'

const TENANT_ID = '8b6f8303-1483-46b7-9950-def93298fa3c'
const domain = 'immateai.com'
const email = 'info@immateai.com'
const products = [
  {slug:'t10-max',name:'T10 MAX',series:'IM Mate',category:'ai-translators',categoryLabel:'AI Translators',tagline:'10-inch dual-screen AI translator for face-to-face business communication',overview:'T10 MAX gives both speakers a dedicated screen so translated content remains visible on each side of the conversation. Customer-supplied product information identifies 0.5-second translation, 96%+ speech-recognition accuracy, 35+ languages, remote video translation and automatically generated conversation minutes.',features:['10-inch dual-screen two-way conversation design','0.5-second translation with 96%+ supplied recognition accuracy','35+ supported languages','Remote video translation and generated conversation minutes','Noise-canceling microphone array'],applications:['Store and hotel reception','Trade-show negotiation','Enterprise meetings','On-site consultation'],advantages:['Both participants can read translated content without passing the device','Commercial desktop format for counter and meeting use','CE and FCC certifications identified in the supplied materials'],specs:{series:'IM Mate',display:'10-inch dual screen',dimensions:'273.58 × 96.5 × 213.48 mm',weight:'1.08 kg',colors:'White / Grey',moq:'100 pieces'},image:'/images/product-t10-max.jpg'},
  {slug:'t5-max',name:'T5 MAX',series:'IM Mate',category:'ai-translators',categoryLabel:'AI Translators',tagline:'Compact dual-screen AI translator for travel and counter service',overview:'T5 MAX is a compact dual-screen translator designed for travel, counter service and cross-region conversations. It works independently through 4G or Wi-Fi and supports online translation plus remote link-based translation.',features:['Compact dual-screen design','Independent 4G and Wi-Fi operation','Online translation','Remote translation through a shared conversation link','Noise-cancellation system','35+ supported languages'],applications:['Travel communication','Retail and service counters','Remote cross-region conversations','International meetings'],advantages:['Private-mold design and design patent identified in supplied materials','Compact format for mobile and counter use','Multiple supplied color options'],specs:{series:'IM Mate',dimensions:'14.4 × 8.48 × 13.58 mm (as supplied)',weight:'0.76 kg',colors:'White / Grey / Pink / Green',moq:'100 pieces'},image:'/images/product-t5-max.jpg'},
  {slug:'c30',name:'C30',series:'IM Cam',category:'video-call-cameras',categoryLabel:'Video Call Cameras',tagline:'2.8-inch two-way video call camera with simple one-button calling',overview:'C30 is an indoor two-way video and audio camera designed for children, older family members and other users who may find phone-based calling difficult. The supplied materials highlight active calling with one-button operation.',features:['2.8-inch display','Two-way video and audio calling','One-button active calling','Indoor communication design'],applications:['Children and family communication','Older-family-member check-ins','Pet monitoring','Indoor remote communication'],advantages:['Simple call control','Integrated camera and display','Compact indoor format'],specs:{series:'IM Cam',display:'2.8-inch',dimensions:'42.2 × 31.9 × 43.6 cm (as supplied)',weight:'0.14 kg',color:'White',moq:'100 pieces'},image:'/images/product-c30.jpg'},
  {slug:'c41p',name:'C41P',series:'IM Cam',category:'video-call-cameras',categoryLabel:'Video Call Cameras',tagline:'4.3-inch two-way video call camera with a built-in speaker',overview:'The C41-series product information describes a 4.3-inch two-way video call camera with a large speaker, 1080p live view, wide-angle pan-tilt coverage, night vision, motion activation and app setup for Android and iOS.',features:['4.3-inch display','1080p live view','360° wide-angle pan-tilt coverage','Night vision','Motion activation','2.4 GHz Wi-Fi','IM Cam app setup for Android and iOS'],applications:['Family video communication','Older-family-member check-ins','Indoor monitoring','Pet monitoring'],advantages:['Larger integrated display and speaker','Wide-angle indoor coverage','Remote setup through the IM Cam app'],specs:{series:'IM Cam',display:'4.3-inch',dimensions:'595 × 455 × 418 mm (as supplied)',weight:'0.34 kg',color:'White',moq:'100 pieces'},image:'/images/product-c41p.jpg'},
]
const categories=[['ai-translators','AI Translators'],['video-call-cameras','Video Call Cameras']]

const required=['NEXT_PUBLIC_SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY']
for(const key of required) if(!process.env[key]) throw new Error(`Missing ${key}`)
const db=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY)

async function main(){
  const passwordHash=await bcrypt.hash('info12345',12)
  const extra_settings={
    translation_profile:{industry:'AI communication devices',company_summary:'Shenzhen Sailan Technology Co., Ltd. develops IM Mate AI translators and IM Cam video call cameras.',main_products:['AI translators','video call cameras'],target_markets:['Global B2B buyers'],glossary:{'IM Mate':'IM Mate','IM Cam':'IM Cam'}},
    site_settings_source:'customer materials',site_settings_initialized_at:new Date().toISOString(),site_settings_manual_fields:[]
  }
  const tenant={id:TENANT_ID,domain,name:'immate',display_name:'深圳市赛蓝科技有限公司',email,password_hash:passwordHash,admin_group:2,brand_color:'#1267d6',logo_url:null,favicon_url:null,site_title_i18n:{en:'immate.ai — AI Translators & Video Call Cameras'},site_tagline_i18n:{en:'Communication hardware for real conversations'},site_description_i18n:{en:'IM Mate AI translators and IM Cam video call cameras from Shenzhen Sailan Technology Co., Ltd.'},default_language:'en',supported_languages:['en'],contact_email:email,contact_phone:'+86 139 2373 9540',contact_whatsapp:'+86 139 2373 9540',contact_address_short:'Shenzhen, Guangdong, China',contact_address_i18n:{en:'Rooms 211–212, Floor 2, Folk Culture Industrial Park, Qunli 2nd Road, Xingdong, Xin’an, Bao’an, Shenzhen, Guangdong, China'},social_links:{},seo_title_i18n:{en:'immate.ai | IM Mate AI Translators & IM Cam Video Call Cameras'},seo_description_i18n:{en:'Explore IM Mate AI translators and IM Cam video call cameras for international B2B applications.'},seo_keywords_i18n:{en:['AI translator','two-way translator','video call camera','IM Mate','IM Cam']},google_analytics_id:null,google_tag_manager_id:null,extra_settings}
  const {data:existingTenant,error:lookupError}=await db.from('tenants').select('id').eq('domain',domain).maybeSingle();if(lookupError)throw lookupError
  const tenantWrite=existingTenant
    ? await db.from('tenants').update(tenant).eq('id',existingTenant.id).select('id,domain,display_name,admin_group').single()
    : await db.from('tenants').insert(tenant).select('id,domain,display_name,admin_group').single()
  if(tenantWrite.error)throw tenantWrite.error
  const tenantId=tenantWrite.data.id
  const {data:conflict}=await db.from('admin_users').select('id,tenant_id').eq('email',email).maybeSingle();if(conflict&&conflict.tenant_id!==tenantId)throw new Error(`Admin email conflict: ${email}`)
  const adminPayload={tenant_id:tenantId,email,password_hash:passwordHash,is_active:true,must_change_password:false}
  const adminWrite=conflict?await db.from('admin_users').update(adminPayload).eq('id',conflict.id):await db.from('admin_users').insert(adminPayload);if(adminWrite.error)throw adminWrite.error
  for(const [slug,name] of categories){const payload={tenant_id:tenantId,slug,name,name_en:name,name_i18n:{en:name},description:`${name} from the ${slug==='ai-translators'?'IM Mate':'IM Cam'} product family.`,description_en:`${name} from the ${slug==='ai-translators'?'IM Mate':'IM Cam'} product family.`,description_i18n:{en:`${name} from the ${slug==='ai-translators'?'IM Mate':'IM Cam'} product family.`},sort_order:slug==='ai-translators'?1:2,is_active:true};const {data:existing}=await db.from('product_categories').select('id').eq('tenant_id',tenantId).eq('slug',slug).maybeSingle();const write=existing?await db.from('product_categories').update(payload).eq('id',existing.id):await db.from('product_categories').insert(payload);if(write.error)throw write.error}
  for(const [i,p] of products.entries()){
    const {data:existing}=await db.from('products').select('id,image_url,extra_data').eq('tenant_id',tenantId).eq('slug',p.slug).maybeSingle()
    const existingExtra=existing?.extra_data&&typeof existing.extra_data==='object'?existing.extra_data:{}
    const existingImage=typeof existing?.image_url==='string'?existing.image_url:''
    const preserveR2=existingImage.includes('.r2.dev/')
    const payload={tenant_id:tenantId,slug:p.slug,name:p.name,name_en:p.name,name_i18n:{en:p.name},model:p.name,category:p.categoryLabel,category_slug:p.category,image_url:preserveR2?existing.image_url:p.image,description:p.tagline,description_en:p.tagline,description_i18n:{en:p.tagline},overview:p.overview,overview_en:p.overview,overview_i18n:{en:p.overview},features:p.features,features_i18n:{en:p.features},applications_i18n:{en:p.applications},advantages_i18n:{en:p.advantages},specs:p.specs,extra_data:preserveR2?{...existingExtra,series:p.series}:{series:p.series,images:[p.image]},sort_order:i+1,is_active:true}
    const write=existing?await db.from('products').update(payload).eq('id',existing.id):await db.from('products').insert(payload)
    if(write.error)throw write.error
  }
  const [{data:tenantRead,error:tr},{data:productRead,error:pr},{data:categoryRead,error:cr},{data:userRead,error:ur}]=await Promise.all([db.from('tenants').select('id,domain,display_name,admin_group,contact_email,default_language,supported_languages,extra_settings').eq('id',tenantId).single(),db.from('products').select('slug,image_url').eq('tenant_id',tenantId).order('sort_order'),db.from('product_categories').select('slug').eq('tenant_id',tenantId).order('sort_order'),db.from('admin_users').select('email,must_change_password').eq('tenant_id',tenantId).single()]);for(const e of [tr,pr,cr,ur])if(e)throw e
  console.log(JSON.stringify({tenant:tenantRead,products:productRead,categories:categoryRead,admin:userRead},null,2))
}
main().catch(error=>{console.error(error.message);process.exit(1)})
